### ISSUE TITLE
Publish the plugin for Java8

### ISSUE THREAD

**Issue by maddingo** [FunThomas424242/plantuml-maven-plugin#21]
When using the plugin in a project that uses Java8, Maven complains with the following error:

[ERROR] Failed to execute goal com.github.funthomas424242:plantuml-maven-plugin:1.5.1:generate (render-plantuml) on project app: Execution render-plantuml of goal com.github.funthomas424242:plantuml-maven-plugin:1.5.1:generate failed: Unable to load the mojo 'generate' in the plugin 'com.github.funthomas424242:plantuml-maven-plugin:1.5.1' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com/github/plantuml/maven/PlantUMLMojo has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

The reason is that the plugin was compiled and targeted for Java 11.
Setting compiler target to 1.8 should fix  this

**Comment by kriegaex** [comment]
If you need a bugfix, enabling the plugin to be used on
  * Java 8+ (before 11+) and
  * Maven 3.0.5+ (before 3.6.3+),
read https://github.com/Huluvu424242/plantuml-maven-plugin/pull/31#issuecomment-852964021.
