### ISSUE TITLE
Add support for a skip property

### ISSUE THREAD

**Issue by bcopy** [FunThomas424242/plantuml-maven-plugin#33]
**Is your feature request related to a problem? Please describe.**
When configuring the plantuml plugin in a parent POM, there should be an easy way to skip the generation (for modules that do not feature any plantuml diagrams for instance)

**Describe the solution you'd like**
If a **skip** configuration property is set to ```true```, the plantuml generate goal is skipped altogether.

**Describe alternatives you've considered**
Only workaround is to configure modules individually

**Comment by Huluvu424242** [comment]
thank you very much for your support.
